# Clase 1 de arquitectura


_Ejemplo de celdas en jupyter_

In [2]:
from nest_asyncio import apply

x = 1
y = 8
x * y

8

_Las celdas tambien pueden importar clases_

In [3]:
import math
math.sin(math.pi/2)

1.0

_Los imports de otra celda funcionan en las celdas siguientes_

In [4]:
math.ceil(3.1)

4

__La instalacion de numpy se hace ejecutando el comando__

`pip install numpy`

In [2]:
import numpy as np

In [6]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [7]:
my_array.ndim

1

In [8]:
my_array.shape

(5,)

In [9]:
my_array2 = np.array([[1, 2, 3], [4, 5, 6]])
my_array2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
my_array2.ndim

2

In [11]:
my_array2.shape

(2, 3)

In [12]:
my_array2.size

6

In [13]:
my_array3 = np.array([[1,2],[3,4],[5,6]])
my_array3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
my_array3.shape

(3, 2)

In [15]:
my_array_3d = np.array([[[1, 2], [3,4]], [[5,6], [7,8]]])
my_array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
my_array_3d.shape

(2, 2, 2)

In [17]:
my_array_3d[0][1][0]

np.int64(3)

In [18]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.random.random((2, 3))

array([[0.52732637, 0.92302994, 0.12746004],
       [0.232541  , 0.96799512, 0.40511692]])

In [21]:
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(5, 20, -2)

array([], dtype=int64)

In [23]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [25]:
np.arange(4, 20).reshape(4, 4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
np.arange(4, 20).reshape(4,4).flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
np.linspace(1, 100, 100).reshape(10, 10)

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [28]:
np.linspace(1, 100, 100)[ : :-1]

array([100.,  99.,  98.,  97.,  96.,  95.,  94.,  93.,  92.,  91.,  90.,
        89.,  88.,  87.,  86.,  85.,  84.,  83.,  82.,  81.,  80.,  79.,
        78.,  77.,  76.,  75.,  74.,  73.,  72.,  71.,  70.,  69.,  68.,
        67.,  66.,  65.,  64.,  63.,  62.,  61.,  60.,  59.,  58.,  57.,
        56.,  55.,  54.,  53.,  52.,  51.,  50.,  49.,  48.,  47.,  46.,
        45.,  44.,  43.,  42.,  41.,  40.,  39.,  38.,  37.,  36.,  35.,
        34.,  33.,  32.,  31.,  30.,  29.,  28.,  27.,  26.,  25.,  24.,
        23.,  22.,  21.,  20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,
        12.,  11.,  10.,   9.,   8.,   7.,   6.,   5.,   4.,   3.,   2.,
         1.])

In [29]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
np.arange(20).reshape(4, 5)[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
np.arange(20).reshape(4, 5)[:3, 1:]


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [32]:
np.arange(20).reshape(4, 5)[:3, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13]])

In [33]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
np.arange(20).reshape(4, 5)[:,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [35]:
np.arange(20).reshape(4, 5)[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [36]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
np.arange(20).reshape(4, 5)[1:,-2::-2]

array([[ 8,  6],
       [13, 11],
       [18, 16]])

In [38]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
np.arange(20).reshape(4, 5)[[1, 0, 3], [1, 3, 4]]

array([ 6,  3, 19])

In [40]:
arr = np.arange(20).reshape(4, 5)
arr[arr > 7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
arr[arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
def is_prime(n):
    if n == 0 or n == 1:
        return False
    i = 2
    while (i ** 2) <= n:
        if n % i == 0:
            return False
        i += 1
    return True

In [43]:
is_prime(20)

False

In [44]:
is_prime(19)

True

In [45]:
is_prime(139)

True

In [46]:
arr = np.arange(1000).reshape(100, 10).flatten()
np.array([x for x in arr if is_prime(x)])

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569,
       571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643,
       647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733,
       739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823,
       827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911,
       919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997])

In [47]:
np.arange(10).reshape(2, 5) - 1

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [48]:
np.arange(10).reshape(2, 5).max()

np.int64(9)

In [49]:
np.arange(10).reshape(2, 5).min()


np.int64(0)

In [50]:
np.arange(10).reshape(2, 5).sum()

np.int64(45)

In [51]:
np.arange(10).reshape(2, 5).transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [52]:
np.arange(10).reshape(2, 5).max(axis=0)

array([5, 6, 7, 8, 9])

In [53]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

In [54]:
a + b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [55]:
a * b

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [56]:
a.dot(b.reshape(5, 2))

array([[160, 170],
       [510, 545]])

In [57]:
# n x m \dot m x n = n x n

In [3]:
import pandas as pd

In [59]:
s = pd.Series([1, 2,4, 5, 9])

In [60]:
s

0    1
1    2
2    4
3    5
4    9
dtype: int64

In [61]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [62]:
dates_serie = pd.date_range('20190101', periods=5)
dates_serie

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05'],
              dtype='datetime64[ns]', freq='D')

In [63]:
dates_serie = pd.date_range('20190101', periods=365)
dates_serie

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [64]:
dates_serie = pd.date_range('20190101', periods=12, freq='ME')
dates_serie

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [65]:
dates_serie = pd.date_range('20241216', periods=10, freq='min')
dates_serie

DatetimeIndex(['2024-12-16 00:00:00', '2024-12-16 00:01:00',
               '2024-12-16 00:02:00', '2024-12-16 00:03:00',
               '2024-12-16 00:04:00', '2024-12-16 00:05:00',
               '2024-12-16 00:06:00', '2024-12-16 00:07:00',
               '2024-12-16 00:08:00', '2024-12-16 00:09:00'],
              dtype='datetime64[ns]', freq='min')

In [66]:
df = pd.DataFrame(
    {
        "Nombre": ['Yadira', 'Roman', 'Valeria', 'Rodrigo', 'Daniel'],
        "Color": ['Naranja', 'Foto', 'Foto', 'Naranja', 'Morado'],
        "Nonce": [2, 5, 4, 6, 7]
    }
)
df

Nombre    Color  Nonce
0   Yadira  Naranja      2
1    Roman     Foto      5
2  Valeria     Foto      4
3  Rodrigo  Naranja      6
4   Daniel   Morado      7

In [67]:
df = pd.DataFrame(
    {
        "Nombre": ['Yadira', 'Roman', 'Valeria', 'Rodrigo', 'Daniel'],
        "Color": ['Naranja', 'Foto', 'Foto', 'Naranja', 'Morado'],
        "Nonce": [2, 5, 4, 6, 7]
    }, index=[1, 2, 3, 4, 5]
)
df

Nombre    Color  Nonce
1   Yadira  Naranja      2
2    Roman     Foto      5
3  Valeria     Foto      4
4  Rodrigo  Naranja      6
5   Daniel   Morado      7

In [68]:
df.sort_values(by='Nombre', ascending=False)

Nombre    Color  Nonce
1   Yadira  Naranja      2
3  Valeria     Foto      4
2    Roman     Foto      5
4  Rodrigo  Naranja      6
5   Daniel   Morado      7

In [69]:
df.describe()

Nonce
count  5.000000
mean   4.800000
std    1.923538
min    2.000000
25%    4.000000
50%    5.000000
75%    6.000000
max    7.000000

In [70]:
df.dtypes

Nombre    object
Color     object
Nonce      int64
dtype: object

In [71]:
df.iloc[4]

Nombre    Daniel
Color     Morado
Nonce          7
Name: 5, dtype: object

In [72]:
df = pd.DataFrame(np.arange(1000).reshape(200, 5), index=pd.date_range('20241216', periods=200, freq='D'), columns=['A', 'B', 'C', 'D', 'E'] )
df

A    B    C    D    E
2024-12-16    0    1    2    3    4
2024-12-17    5    6    7    8    9
2024-12-18   10   11   12   13   14
2024-12-19   15   16   17   18   19
2024-12-20   20   21   22   23   24
...         ...  ...  ...  ...  ...
2025-06-29  975  976  977  978  979
2025-06-30  980  981  982  983  984
2025-07-01  985  986  987  988  989
2025-07-02  990  991  992  993  994
2025-07-03  995  996  997  998  999

[200 rows x 5 columns]

In [73]:
# REST API
df.head()

A   B   C   D   E
2024-12-16   0   1   2   3   4
2024-12-17   5   6   7   8   9
2024-12-18  10  11  12  13  14
2024-12-19  15  16  17  18  19
2024-12-20  20  21  22  23  24

In [74]:
df.tail()

A    B    C    D    E
2025-06-29  975  976  977  978  979
2025-06-30  980  981  982  983  984
2025-07-01  985  986  987  988  989
2025-07-02  990  991  992  993  994
2025-07-03  995  996  997  998  999

In [75]:
df.dtypes

A    int64
B    int64
C    int64
D    int64
E    int64
dtype: object

In [76]:
df.head(10)

A   B   C   D   E
2024-12-16   0   1   2   3   4
2024-12-17   5   6   7   8   9
2024-12-18  10  11  12  13  14
2024-12-19  15  16  17  18  19
2024-12-20  20  21  22  23  24
2024-12-21  25  26  27  28  29
2024-12-22  30  31  32  33  34
2024-12-23  35  36  37  38  39
2024-12-24  40  41  42  43  44
2024-12-25  45  46  47  48  49

In [77]:
df.tail(20)

A    B    C    D    E
2025-06-14  900  901  902  903  904
2025-06-15  905  906  907  908  909
2025-06-16  910  911  912  913  914
2025-06-17  915  916  917  918  919
2025-06-18  920  921  922  923  924
2025-06-19  925  926  927  928  929
2025-06-20  930  931  932  933  934
2025-06-21  935  936  937  938  939
2025-06-22  940  941  942  943  944
2025-06-23  945  946  947  948  949
2025-06-24  950  951  952  953  954
2025-06-25  955  956  957  958  959
2025-06-26  960  961  962  963  964
2025-06-27  965  966  967  968  969
2025-06-28  970  971  972  973  974
2025-06-29  975  976  977  978  979
2025-06-30  980  981  982  983  984
2025-07-01  985  986  987  988  989
2025-07-02  990  991  992  993  994
2025-07-03  995  996  997  998  999

In [78]:
df.index

DatetimeIndex(['2024-12-16', '2024-12-17', '2024-12-18', '2024-12-19',
               '2024-12-20', '2024-12-21', '2024-12-22', '2024-12-23',
               '2024-12-24', '2024-12-25',
               ...
               '2025-06-24', '2025-06-25', '2025-06-26', '2025-06-27',
               '2025-06-28', '2025-06-29', '2025-06-30', '2025-07-01',
               '2025-07-02', '2025-07-03'],
              dtype='datetime64[ns]', length=200, freq='D')

In [79]:
my_numpy_particles = df.to_numpy()
my_numpy_particles

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 1

In [80]:
df.describe()

A           B           C           D           E
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   497.500000  498.500000  499.500000  500.500000  501.500000
std    289.395923  289.395923  289.395923  289.395923  289.395923
min      0.000000    1.000000    2.000000    3.000000    4.000000
25%    248.750000  249.750000  250.750000  251.750000  252.750000
50%    497.500000  498.500000  499.500000  500.500000  501.500000
75%    746.250000  747.250000  748.250000  749.250000  750.250000
max    995.000000  996.000000  997.000000  998.000000  999.000000

In [81]:
df.sort_index(ascending=False)

A    B    C    D    E
2025-07-03  995  996  997  998  999
2025-07-02  990  991  992  993  994
2025-07-01  985  986  987  988  989
2025-06-30  980  981  982  983  984
2025-06-29  975  976  977  978  979
...         ...  ...  ...  ...  ...
2024-12-20   20   21   22   23   24
2024-12-19   15   16   17   18   19
2024-12-18   10   11   12   13   14
2024-12-17    5    6    7    8    9
2024-12-16    0    1    2    3    4

[200 rows x 5 columns]

In [82]:
df["D"]

2024-12-16      3
2024-12-17      8
2024-12-18     13
2024-12-19     18
2024-12-20     23
             ... 
2025-06-29    978
2025-06-30    983
2025-07-01    988
2025-07-02    993
2025-07-03    998
Freq: D, Name: D, Length: 200, dtype: int64

In [83]:
df[1:10]

A   B   C   D   E
2024-12-17   5   6   7   8   9
2024-12-18  10  11  12  13  14
2024-12-19  15  16  17  18  19
2024-12-20  20  21  22  23  24
2024-12-21  25  26  27  28  29
2024-12-22  30  31  32  33  34
2024-12-23  35  36  37  38  39
2024-12-24  40  41  42  43  44
2024-12-25  45  46  47  48  49

In [84]:
df['20241220':'20250106']

A    B    C    D    E
2024-12-20   20   21   22   23   24
2024-12-21   25   26   27   28   29
2024-12-22   30   31   32   33   34
2024-12-23   35   36   37   38   39
2024-12-24   40   41   42   43   44
2024-12-25   45   46   47   48   49
2024-12-26   50   51   52   53   54
2024-12-27   55   56   57   58   59
2024-12-28   60   61   62   63   64
2024-12-29   65   66   67   68   69
2024-12-30   70   71   72   73   74
2024-12-31   75   76   77   78   79
2025-01-01   80   81   82   83   84
2025-01-02   85   86   87   88   89
2025-01-03   90   91   92   93   94
2025-01-04   95   96   97   98   99
2025-01-05  100  101  102  103  104
2025-01-06  105  106  107  108  109

In [4]:
my_data = pd.read_csv('datos_prueba.csv')

In [86]:
my_data

Tabla de usuarios de no se que Unnamed: 1 Unnamed: 2          Unnamed: 3  \
0                           Nombre       Edad     Ciudad             Salario   
1                         Nombre_0         56   Ciudad_B   35631.59153789031   
2                         Nombre_1         35   Ciudad_D   53368.49795948443   
3                         Nombre_2         34   Ciudad_E   52673.34215540657   
4                         Nombre_3         25   Ciudad_E   47408.38775810768   
..                             ...        ...        ...                 ...   
96                       Nombre_95         50   Ciudad_D  26066.762231061923   
97                       Nombre_96         37   Ciudad_D   48004.09261357822   
98                       Nombre_97         51   Ciudad_C   41881.68516646321   
99                       Nombre_98         46   Ciudad_A   43308.35192089291   
100                      Nombre_99         50   Ciudad_C   55129.19705385575   

           Unnamed: 4 Unnamed: 5  
0    Fecha_Nacimiento     Género  
1          1992-08-13  Masculino  
2          1975-07-04  Masculino  
3          1991-05-09  Masculino  
4          1977-12-10  Masculino  
..                ...        ...  
96         1986-12-29   Femenino  
97         1994-08-10   Femenino  
98         1979-06-17  Masculino  
99         1995-10-28  Masculino  
100        1977-02-03   Femenino  

[101 rows x 6 columns]

In [87]:
my_data.shape

(101, 6)

In [88]:
my_data.index

RangeIndex(start=0, stop=101, step=1)

In [89]:
my_data.columns

Index(['Tabla de usuarios de no se que', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5'],
      dtype='object')

In [36]:
my_data = pd.read_csv('datos_prueba.csv', names=['nombre', 'edad', 'ciudad', 'salario', 'datebirth', 'genero'], header=1)

In [91]:
my_data

nombre  edad    ciudad       salario   datebirth     genero
0    Nombre_0    56  Ciudad_B  35631.591538  1992-08-13  Masculino
1    Nombre_1    35  Ciudad_D  53368.497959  1975-07-04  Masculino
2    Nombre_2    34  Ciudad_E  52673.342155  1991-05-09  Masculino
3    Nombre_3    25  Ciudad_E  47408.387758  1977-12-10  Masculino
4    Nombre_4    28  Ciudad_C  25012.284767  1995-06-22   Femenino
..        ...   ...       ...           ...         ...        ...
95  Nombre_95    50  Ciudad_D  26066.762231  1986-12-29   Femenino
96  Nombre_96    37  Ciudad_D  48004.092614  1994-08-10   Femenino
97  Nombre_97    51  Ciudad_C  41881.685166  1979-06-17  Masculino
98  Nombre_98    46  Ciudad_A  43308.351921  1995-10-28  Masculino
99  Nombre_99    50  Ciudad_C  55129.197054  1977-02-03   Femenino

[100 rows x 6 columns]

In [92]:
my_data[0:50]

nombre  edad    ciudad       salario   datebirth     genero
0    Nombre_0    56  Ciudad_B  35631.591538  1992-08-13  Masculino
1    Nombre_1    35  Ciudad_D  53368.497959  1975-07-04  Masculino
2    Nombre_2    34  Ciudad_E  52673.342155  1991-05-09  Masculino
3    Nombre_3    25  Ciudad_E  47408.387758  1977-12-10  Masculino
4    Nombre_4    28  Ciudad_C  25012.284767  1995-06-22   Femenino
5    Nombre_5    55  Ciudad_E  42851.667035  1987-12-20   Femenino
6    Nombre_6    58  Ciudad_C  26330.730752  1999-08-17   Femenino
7    Nombre_7    51  Ciudad_A  59094.914830  1981-10-14        NaN
8    Nombre_8    54  Ciudad_B  38854.451859  1977-10-12  Masculino
9    Nombre_9    37  Ciudad_D  38870.163069  2004-08-07   Femenino
10  Nombre_10    52  Ciudad_C  27267.591595  2000-11-11  Masculino
11  Nombre_11    50  Ciudad_E  28754.083283  1995-12-29  Masculino
12  Nombre_12    49  Ciudad_C  49944.883529  1997-01-16   Femenino
13  Nombre_13    52  Ciudad_B  32237.897772  1984-10-29  Masculino
14  Nombre_14    21  Ciudad_B  38479.648791  1986-07-22   Femenino
15  Nombre_15    18  Ciudad_D  51328.527738  1994-08-02   Femenino
16  Nombre_16    30  Ciudad_E  41392.601296  1990-03-16   Femenino
17  Nombre_17    37  Ciudad_E  58053.023691  1966-02-18  Masculino
18  Nombre_18    36  Ciudad_E  31316.960507  1979-09-27   femenino
19  Nombre_19    36  Ciudad_C  48064.981954  1974-06-15   Femenino
20  Nombre_20    44  Ciudad_B  43091.955139  1967-11-14  Masculino
21  Nombre_21    32  Ciudad_D  37485.213075  1994-01-18   Femenino
22  Nombre_22    32  Ciudad_D  59593.064102  1996-11-12  Masculino
23  Nombre_23    59  Ciudad_A  40409.484746  1996-09-04  Masculino
24  Nombre_24    55  Ciudad_A  30036.673796  1970-01-29   Femenino
25  Nombre_25    52  Ciudad_D  34061.272201  1979-12-31   Femenino
26  Nombre_26    33  Ciudad_C  44308.139282  1975-05-05   Femenino
27  Nombre_27    24  Ciudad_C  42238.139951  1995-02-10   Femenino
28  Nombre_28    46  Ciudad_A  50971.629796  1970-01-20   Femenino
29  Nombre_29    19  Ciudad_B  48789.065642  2001-09-01  Masculino
30  Nombre_30    42  Ciudad_A  46610.206381  1964-07-08   Femenino
31  Nombre_31    48  Ciudad_E  35217.688653  1997-11-15  Masculino
32  Nombre_32    41  Ciudad_B  51871.370462  1983-12-22    Femenin
33  Nombre_33    24  Ciudad_C  51130.650596  1991-08-29   Femenino
34  Nombre_34    44  Ciudad_C  53044.265479  1994-04-20   Femenino
35  Nombre_35    41  Ciudad_C  51006.072731  1996-08-01   Femenino
36  Nombre_36    27  Ciudad_D  46403.283972  2003-02-11  Masculino
37  Nombre_37    56  Ciudad_D  43443.213044  1979-12-15  Masculino
38  Nombre_38    31  Ciudad_E  33136.593997  1990-10-12  Masculino
39  Nombre_39    21  Ciudad_C  59835.409428  1969-04-11  Masculino
40  Nombre_40    53  Ciudad_D  45050.894398  1992-02-14   Femenino
41  Nombre_41    54  Ciudad_A  25615.292451  1964-02-03   Femenino
42  Nombre_42    27  Ciudad_E  49152.626278  1992-03-11  masculino
43  Nombre_43    26  Ciudad_C  27048.303259  1977-08-20   Femenino
44  Nombre_44    56  Ciudad_B  49992.354046  1971-08-24   Femenino
45  Nombre_45    34  Ciudad_B  50964.059595  1980-11-03   Femenino
46  Nombre_46    46  Ciudad_C  56336.314674  1983-10-01   Femenino
47  Nombre_47    55  Ciudad_D  34457.550454  1969-01-26  Masculino
48  Nombre_48    41  Ciudad_A  59749.242461  1996-10-26   Femenino
49  Nombre_49    48  Ciudad_B  44684.006767  1973-04-21  Masculino

In [93]:
my_data.loc[50:60,["datebirth", "genero"]]

datebirth     genero
50  1968-05-16  Masculino
51  1988-03-08  Masculino
52  2001-08-15  Masculino
53  1989-07-23   Femenino
54  1970-09-26   Femenino
55  1986-07-18  Masculino
56  1976-08-04   Femenino
57  1967-06-28   Femenino
58  1968-03-17  Masculino
59  2003-07-24   Femenino
60  1981-08-22   Femenino

In [94]:
type(my_data.loc[50:60,["datebirth", "genero"]])

pandas.core.frame.DataFrame

In [95]:
my_data.loc[0, "nombre"]

'Nombre_0'

In [96]:
type(my_data.loc[0, "nombre"])

str

In [97]:
my_data.loc[10:30, "ciudad"]

10    Ciudad_C
11    Ciudad_E
12    Ciudad_C
13    Ciudad_B
14    Ciudad_B
15    Ciudad_D
16    Ciudad_E
17    Ciudad_E
18    Ciudad_E
19    Ciudad_C
20    Ciudad_B
21    Ciudad_D
22    Ciudad_D
23    Ciudad_A
24    Ciudad_A
25    Ciudad_D
26    Ciudad_C
27    Ciudad_C
28    Ciudad_A
29    Ciudad_B
30    Ciudad_A
Name: ciudad, dtype: object

In [98]:
my_data.loc[10:30, "ciudad"]

10    Ciudad_C
11    Ciudad_E
12    Ciudad_C
13    Ciudad_B
14    Ciudad_B
15    Ciudad_D
16    Ciudad_E
17    Ciudad_E
18    Ciudad_E
19    Ciudad_C
20    Ciudad_B
21    Ciudad_D
22    Ciudad_D
23    Ciudad_A
24    Ciudad_A
25    Ciudad_D
26    Ciudad_C
27    Ciudad_C
28    Ciudad_A
29    Ciudad_B
30    Ciudad_A
Name: ciudad, dtype: object

In [99]:
my_data.iloc[10:30, 2]

10    Ciudad_C
11    Ciudad_E
12    Ciudad_C
13    Ciudad_B
14    Ciudad_B
15    Ciudad_D
16    Ciudad_E
17    Ciudad_E
18    Ciudad_E
19    Ciudad_C
20    Ciudad_B
21    Ciudad_D
22    Ciudad_D
23    Ciudad_A
24    Ciudad_A
25    Ciudad_D
26    Ciudad_C
27    Ciudad_C
28    Ciudad_A
29    Ciudad_B
Name: ciudad, dtype: object

In [100]:
my_data.iloc[10:30, 0:2]

nombre  edad
10  Nombre_10    52
11  Nombre_11    50
12  Nombre_12    49
13  Nombre_13    52
14  Nombre_14    21
15  Nombre_15    18
16  Nombre_16    30
17  Nombre_17    37
18  Nombre_18    36
19  Nombre_19    36
20  Nombre_20    44
21  Nombre_21    32
22  Nombre_22    32
23  Nombre_23    59
24  Nombre_24    55
25  Nombre_25    52
26  Nombre_26    33
27  Nombre_27    24
28  Nombre_28    46
29  Nombre_29    19

In [101]:
my_data.iloc[10:30, [0, 5]]

nombre     genero
10  Nombre_10  Masculino
11  Nombre_11  Masculino
12  Nombre_12   Femenino
13  Nombre_13  Masculino
14  Nombre_14   Femenino
15  Nombre_15   Femenino
16  Nombre_16   Femenino
17  Nombre_17  Masculino
18  Nombre_18   femenino
19  Nombre_19   Femenino
20  Nombre_20  Masculino
21  Nombre_21   Femenino
22  Nombre_22  Masculino
23  Nombre_23  Masculino
24  Nombre_24   Femenino
25  Nombre_25   Femenino
26  Nombre_26   Femenino
27  Nombre_27   Femenino
28  Nombre_28   Femenino
29  Nombre_29  Masculino

In [102]:
my_data.iloc[[0, 1, 2, 28], [0, 5]]

nombre     genero
0    Nombre_0  Masculino
1    Nombre_1  Masculino
2    Nombre_2  Masculino
28  Nombre_28   Femenino

In [103]:
my_data.iloc[9, 3]

np.float64(38870.163069441405)

In [104]:
my_data.iloc[1, 4]

'1975-07-04'

In [105]:
my_data[my_data["salario"] > 30000]

nombre  edad    ciudad       salario   datebirth     genero
0    Nombre_0    56  Ciudad_B  35631.591538  1992-08-13  Masculino
1    Nombre_1    35  Ciudad_D  53368.497959  1975-07-04  Masculino
2    Nombre_2    34  Ciudad_E  52673.342155  1991-05-09  Masculino
3    Nombre_3    25  Ciudad_E  47408.387758  1977-12-10  Masculino
5    Nombre_5    55  Ciudad_E  42851.667035  1987-12-20   Femenino
..        ...   ...       ...           ...         ...        ...
94  Nombre_94    50  Ciudad_B  38502.603617  1982-08-30  Masculino
96  Nombre_96    37  Ciudad_D  48004.092614  1994-08-10   Femenino
97  Nombre_97    51  Ciudad_C  41881.685166  1979-06-17  Masculino
98  Nombre_98    46  Ciudad_A  43308.351921  1995-10-28  Masculino
99  Nombre_99    50  Ciudad_C  55129.197054  1977-02-03   Femenino

[87 rows x 6 columns]

In [106]:
my_data.loc[10:20, "genero"]

10    Masculino
11    Masculino
12     Femenino
13    Masculino
14     Femenino
15     Femenino
16     Femenino
17    Masculino
18     femenino
19     Femenino
20    Masculino
Name: genero, dtype: object

In [107]:
my_data[my_data["datebirth"] > '2000-01-01']

nombre  edad    ciudad       salario   datebirth     genero
9    Nombre_9    37  Ciudad_D  38870.163069  2004-08-07   Femenino
10  Nombre_10    52  Ciudad_C  27267.591595  2000-11-11  Masculino
29  Nombre_29    19  Ciudad_B  48789.065642  2001-09-01  Masculino
36  Nombre_36    27  Ciudad_D  46403.283972  2003-02-11  Masculino
52  Nombre_52    56  Ciudad_D  58325.156847  2001-08-15  Masculino
59  Nombre_59    41  Ciudad_A  43302.628104  2003-07-24   Femenino
64  Nombre_64    43  Ciudad_D  56319.364652  2004-03-27  Masculino
78  Nombre_78    44  Ciudad_C  57768.840033  2005-12-18  Masculino
87  Nombre_87    56  Ciudad_E  45583.606766  2000-07-11   Femenino
91  Nombre_91    51  Ciudad_E  51568.157966  2001-06-10   Femenino
93  Nombre_93    30  Ciudad_A  43717.695672  2002-07-14   Femenino

In [108]:
my_data[my_data["genero"] == 'Femenino'].shape[0]

52

In [109]:
my_data[my_data["genero"] == 'Masculino'].shape[0]

44

In [110]:
my_data[my_data["edad"] >= 40]

nombre  edad    ciudad       salario   datebirth     genero
0    Nombre_0    56  Ciudad_B  35631.591538  1992-08-13  Masculino
5    Nombre_5    55  Ciudad_E  42851.667035  1987-12-20   Femenino
6    Nombre_6    58  Ciudad_C  26330.730752  1999-08-17   Femenino
7    Nombre_7    51  Ciudad_A  59094.914830  1981-10-14        NaN
8    Nombre_8    54  Ciudad_B  38854.451859  1977-10-12  Masculino
10  Nombre_10    52  Ciudad_C  27267.591595  2000-11-11  Masculino
11  Nombre_11    50  Ciudad_E  28754.083283  1995-12-29  Masculino
12  Nombre_12    49  Ciudad_C  49944.883529  1997-01-16   Femenino
13  Nombre_13    52  Ciudad_B  32237.897772  1984-10-29  Masculino
20  Nombre_20    44  Ciudad_B  43091.955139  1967-11-14  Masculino
23  Nombre_23    59  Ciudad_A  40409.484746  1996-09-04  Masculino
24  Nombre_24    55  Ciudad_A  30036.673796  1970-01-29   Femenino
25  Nombre_25    52  Ciudad_D  34061.272201  1979-12-31   Femenino
28  Nombre_28    46  Ciudad_A  50971.629796  1970-01-20   Femenino
30  Nombre_30    42  Ciudad_A  46610.206381  1964-07-08   Femenino
31  Nombre_31    48  Ciudad_E  35217.688653  1997-11-15  Masculino
32  Nombre_32    41  Ciudad_B  51871.370462  1983-12-22    Femenin
34  Nombre_34    44  Ciudad_C  53044.265479  1994-04-20   Femenino
35  Nombre_35    41  Ciudad_C  51006.072731  1996-08-01   Femenino
37  Nombre_37    56  Ciudad_D  43443.213044  1979-12-15  Masculino
40  Nombre_40    53  Ciudad_D  45050.894398  1992-02-14   Femenino
41  Nombre_41    54  Ciudad_A  25615.292451  1964-02-03   Femenino
44  Nombre_44    56  Ciudad_B  49992.354046  1971-08-24   Femenino
46  Nombre_46    46  Ciudad_C  56336.314674  1983-10-01   Femenino
47  Nombre_47    55  Ciudad_D  34457.550454  1969-01-26  Masculino
48  Nombre_48    41  Ciudad_A  59749.242461  1996-10-26   Femenino
49  Nombre_49    48  Ciudad_B  44684.006767  1973-04-21  Masculino
50  Nombre_50    56  Ciudad_E  58893.691313  1968-05-16  Masculino
52  Nombre_52    56  Ciudad_D  58325.156847  2001-08-15  Masculino
53  Nombre_53    59  Ciudad_B  55745.620666  1989-07-23   Femenino
59  Nombre_59    41  Ciudad_A  43302.628104  2003-07-24   Femenino
63  Nombre_63    41  Ciudad_B  51839.135612  1974-05-04   Femenino
64  Nombre_64    43  Ciudad_D  56319.364652  2004-03-27  Masculino
67  Nombre_67    44  Ciudad_D  57479.582226  1978-10-20   Femenino
69  Nombre_69    52  Ciudad_D  56687.234058  1998-12-29   Femenino
71  Nombre_71    57  Ciudad_D  45365.479177  1974-01-03   Femenino
72  Nombre_72    50  Ciudad_C  51753.260565  1972-11-25   Femenino
75  Nombre_75    42  Ciudad_C  29445.981274  1986-06-30  Masculino
76  Nombre_76    45  Ciudad_E  46867.515976  1987-05-28   Femenino
77  Nombre_77    58  Ciudad_D  34709.957479  1998-01-10   Femenino
78  Nombre_78    44  Ciudad_C  57768.840033  2005-12-18  Masculino
81  Nombre_81    44  Ciudad_B  49677.168059  1972-06-18  Masculino
82  Nombre_82    45  Ciudad_B  54184.992764  1970-10-27  Masculino
84  Nombre_84    41  Ciudad_D  47367.694734  1989-02-07   Femenino
87  Nombre_87    56  Ciudad_E  45583.606766  2000-07-11   Femenino
88  Nombre_88    57  Ciudad_E  39461.958819  1991-03-17   Femenino
89  Nombre_89    50  Ciudad_A  51894.903796  1969-04-06   Femenino
91  Nombre_91    51  Ciudad_E  51568.157966  2001-06-10   Femenino
92  Nombre_92    52  Ciudad_C  38650.108600  1968-06-15  Masculino
94  Nombre_94    50  Ciudad_B  38502.603617  1982-08-30  Masculino
95  Nombre_95    50  Ciudad_D  26066.762231  1986-12-29   Femenino
97  Nombre_97    51  Ciudad_C  41881.685166  1979-06-17  Masculino
98  Nombre_98    46  Ciudad_A  43308.351921  1995-10-28  Masculino
99  Nombre_99    50  Ciudad_C  55129.197054  1977-02-03   Femenino

In [111]:
my_data.shape

(100, 6)

In [112]:
my_data[(my_data["edad"] >= 40 ) & (my_data["edad"] <= 50 )]

nombre  edad    ciudad       salario   datebirth     genero
11  Nombre_11    50  Ciudad_E  28754.083283  1995-12-29  Masculino
12  Nombre_12    49  Ciudad_C  49944.883529  1997-01-16   Femenino
20  Nombre_20    44  Ciudad_B  43091.955139  1967-11-14  Masculino
28  Nombre_28    46  Ciudad_A  50971.629796  1970-01-20   Femenino
30  Nombre_30    42  Ciudad_A  46610.206381  1964-07-08   Femenino
31  Nombre_31    48  Ciudad_E  35217.688653  1997-11-15  Masculino
32  Nombre_32    41  Ciudad_B  51871.370462  1983-12-22    Femenin
34  Nombre_34    44  Ciudad_C  53044.265479  1994-04-20   Femenino
35  Nombre_35    41  Ciudad_C  51006.072731  1996-08-01   Femenino
46  Nombre_46    46  Ciudad_C  56336.314674  1983-10-01   Femenino
48  Nombre_48    41  Ciudad_A  59749.242461  1996-10-26   Femenino
49  Nombre_49    48  Ciudad_B  44684.006767  1973-04-21  Masculino
59  Nombre_59    41  Ciudad_A  43302.628104  2003-07-24   Femenino
63  Nombre_63    41  Ciudad_B  51839.135612  1974-05-04   Femenino
64  Nombre_64    43  Ciudad_D  56319.364652  2004-03-27  Masculino
67  Nombre_67    44  Ciudad_D  57479.582226  1978-10-20   Femenino
72  Nombre_72    50  Ciudad_C  51753.260565  1972-11-25   Femenino
75  Nombre_75    42  Ciudad_C  29445.981274  1986-06-30  Masculino
76  Nombre_76    45  Ciudad_E  46867.515976  1987-05-28   Femenino
78  Nombre_78    44  Ciudad_C  57768.840033  2005-12-18  Masculino
81  Nombre_81    44  Ciudad_B  49677.168059  1972-06-18  Masculino
82  Nombre_82    45  Ciudad_B  54184.992764  1970-10-27  Masculino
84  Nombre_84    41  Ciudad_D  47367.694734  1989-02-07   Femenino
89  Nombre_89    50  Ciudad_A  51894.903796  1969-04-06   Femenino
94  Nombre_94    50  Ciudad_B  38502.603617  1982-08-30  Masculino
95  Nombre_95    50  Ciudad_D  26066.762231  1986-12-29   Femenino
98  Nombre_98    46  Ciudad_A  43308.351921  1995-10-28  Masculino
99  Nombre_99    50  Ciudad_C  55129.197054  1977-02-03   Femenino

In [113]:
# Todos los nombres de las personas que viven en la ciudad Ciudad_E y que ganan menos de 20,000 pesos.
data_frame_personas_afortunadas = my_data[(my_data["ciudad"] == 'Ciudad_E') & (my_data["salario"] < 30000)]
data_frame_personas_afortunadas

nombre  edad    ciudad       salario   datebirth     genero
11  Nombre_11    50  Ciudad_E  28754.083283  1995-12-29  Masculino
58  Nombre_58    33  Ciudad_E  25127.846069  1968-03-17  Masculino

In [114]:
my_data[my_data["ciudad"].isin(["Ciudad_A", "Ciudad_B", "Ciudad_C"])]

nombre  edad    ciudad       salario   datebirth     genero
0    Nombre_0    56  Ciudad_B  35631.591538  1992-08-13  Masculino
4    Nombre_4    28  Ciudad_C  25012.284767  1995-06-22   Femenino
6    Nombre_6    58  Ciudad_C  26330.730752  1999-08-17   Femenino
7    Nombre_7    51  Ciudad_A  59094.914830  1981-10-14        NaN
8    Nombre_8    54  Ciudad_B  38854.451859  1977-10-12  Masculino
10  Nombre_10    52  Ciudad_C  27267.591595  2000-11-11  Masculino
12  Nombre_12    49  Ciudad_C  49944.883529  1997-01-16   Femenino
13  Nombre_13    52  Ciudad_B  32237.897772  1984-10-29  Masculino
14  Nombre_14    21  Ciudad_B  38479.648791  1986-07-22   Femenino
19  Nombre_19    36  Ciudad_C  48064.981954  1974-06-15   Femenino
20  Nombre_20    44  Ciudad_B  43091.955139  1967-11-14  Masculino
23  Nombre_23    59  Ciudad_A  40409.484746  1996-09-04  Masculino
24  Nombre_24    55  Ciudad_A  30036.673796  1970-01-29   Femenino
26  Nombre_26    33  Ciudad_C  44308.139282  1975-05-05   Femenino
27  Nombre_27    24  Ciudad_C  42238.139951  1995-02-10   Femenino
28  Nombre_28    46  Ciudad_A  50971.629796  1970-01-20   Femenino
29  Nombre_29    19  Ciudad_B  48789.065642  2001-09-01  Masculino
30  Nombre_30    42  Ciudad_A  46610.206381  1964-07-08   Femenino
32  Nombre_32    41  Ciudad_B  51871.370462  1983-12-22    Femenin
33  Nombre_33    24  Ciudad_C  51130.650596  1991-08-29   Femenino
34  Nombre_34    44  Ciudad_C  53044.265479  1994-04-20   Femenino
35  Nombre_35    41  Ciudad_C  51006.072731  1996-08-01   Femenino
39  Nombre_39    21  Ciudad_C  59835.409428  1969-04-11  Masculino
41  Nombre_41    54  Ciudad_A  25615.292451  1964-02-03   Femenino
43  Nombre_43    26  Ciudad_C  27048.303259  1977-08-20   Femenino
44  Nombre_44    56  Ciudad_B  49992.354046  1971-08-24   Femenino
45  Nombre_45    34  Ciudad_B  50964.059595  1980-11-03   Femenino
46  Nombre_46    46  Ciudad_C  56336.314674  1983-10-01   Femenino
48  Nombre_48    41  Ciudad_A  59749.242461  1996-10-26   Femenino
49  Nombre_49    48  Ciudad_B  44684.006767  1973-04-21  Masculino
51  Nombre_51    39  Ciudad_B  36713.001724  1988-03-08  Masculino
53  Nombre_53    59  Ciudad_B  55745.620666  1989-07-23   Femenino
55  Nombre_55    33  Ciudad_C  51201.460494  1986-07-18  Masculino
56  Nombre_56    32  Ciudad_C  25013.574517  1976-08-04   Femenino
59  Nombre_59    41  Ciudad_A  43302.628104  2003-07-24   Femenino
60  Nombre_60    39  Ciudad_B  28427.229675  1981-08-22   Femenino
61  Nombre_61    23  Ciudad_A  32101.063470  1993-08-22  Masculino
62  Nombre_62    37  Ciudad_A  54797.486757  1980-07-28  Masculino
63  Nombre_63    41  Ciudad_B  51839.135612  1974-05-04   Femenino
65  Nombre_65    27  Ciudad_A  30869.132704  1966-04-08   Femenino
70  Nombre_70    21  Ciudad_A  36488.994131  1994-09-27  Masculino
72  Nombre_72    50  Ciudad_C  51753.260565  1972-11-25   Femenino
75  Nombre_75    42  Ciudad_C  29445.981274  1986-06-30  Masculino
78  Nombre_78    44  Ciudad_C  57768.840033  2005-12-18  Masculino
80  Nombre_80    23  Ciudad_C  44756.189860  1985-12-23  Masculino
81  Nombre_81    44  Ciudad_B  49677.168059  1972-06-18  Masculino
82  Nombre_82    45  Ciudad_B  54184.992764  1970-10-27  Masculino
83  Nombre_83    22  Ciudad_C  38381.487231  1964-11-08  Masculino
85  Nombre_85    29  Ciudad_C  28699.048420  1979-06-23   Femenino
86  Nombre_86    34  Ciudad_A  54336.181996  1999-01-28  Masculino
89  Nombre_89    50  Ciudad_A  51894.903796  1969-04-06   Femenino
92  Nombre_92    52  Ciudad_C  38650.108600  1968-06-15  Masculino
93  Nombre_93    30  Ciudad_A  43717.695672  2002-07-14   Femenino
94  Nombre_94    50  Ciudad_B  38502.603617  1982-08-30  Masculino
97  Nombre_97    51  Ciudad_C  41881.685166  1979-06-17  Masculino
98  Nombre_98    46  Ciudad_A  43308.351921  1995-10-28  Masculino
99  Nombre_99    50  Ciudad_C  55129.197054  1977-02-03   Femenino

In [115]:
my_data.iloc[:,1:]

edad    ciudad       salario   datebirth     genero
0     56  Ciudad_B  35631.591538  1992-08-13  Masculino
1     35  Ciudad_D  53368.497959  1975-07-04  Masculino
2     34  Ciudad_E  52673.342155  1991-05-09  Masculino
3     25  Ciudad_E  47408.387758  1977-12-10  Masculino
4     28  Ciudad_C  25012.284767  1995-06-22   Femenino
..   ...       ...           ...         ...        ...
95    50  Ciudad_D  26066.762231  1986-12-29   Femenino
96    37  Ciudad_D  48004.092614  1994-08-10   Femenino
97    51  Ciudad_C  41881.685166  1979-06-17  Masculino
98    46  Ciudad_A  43308.351921  1995-10-28  Masculino
99    50  Ciudad_C  55129.197054  1977-02-03   Femenino

[100 rows x 5 columns]

In [116]:
my_data.drop("salario", axis=1)

nombre  edad    ciudad   datebirth     genero
0    Nombre_0    56  Ciudad_B  1992-08-13  Masculino
1    Nombre_1    35  Ciudad_D  1975-07-04  Masculino
2    Nombre_2    34  Ciudad_E  1991-05-09  Masculino
3    Nombre_3    25  Ciudad_E  1977-12-10  Masculino
4    Nombre_4    28  Ciudad_C  1995-06-22   Femenino
..        ...   ...       ...         ...        ...
95  Nombre_95    50  Ciudad_D  1986-12-29   Femenino
96  Nombre_96    37  Ciudad_D  1994-08-10   Femenino
97  Nombre_97    51  Ciudad_C  1979-06-17  Masculino
98  Nombre_98    46  Ciudad_A  1995-10-28  Masculino
99  Nombre_99    50  Ciudad_C  1977-02-03   Femenino

[100 rows x 5 columns]

In [117]:
def round2(numero):
    return np.round(numero, 2)

def round1(numero):
    return np.round(numero, 1)

def suma_redondeado(a, b, f):
    return f(a) + f(b)

suma_redondeado(1.55, 0.55, round1)

np.float64(2.2)

In [118]:
suma_redondeado(1.55, 0.55, lambda x: np.round(x, 0))

np.float64(3.0)

In [119]:
suma_redondeado(1.55, 0.55, lambda x: (np.ceil(x) + np.floor(x))/2)

np.float64(2.0)

In [120]:
array_example = np.arange(100)
np.array([x**2 for x in array_example])

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [121]:
def pow2(x):
    return x**2
np.array([pow2(x) for x in array_example])

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [122]:
resultado = np.array([(lambda y: y**2)(x) for x in array_example])

In [ ]:
generator = [x**2 for x in range(999999999999999999999999999999999999999999999)]

In [208]:
np.array(array_example)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [212]:
def reduce(my_lista, function_to_apply):
    return function_to_apply(my_lista)

def suma(my_lista):
    resultado = 0
    for x in my_lista:
        resultado += x
    return resultado

def multiplica(my_lista):
    resultado = 1
    for x in my_lista:
        resultado *= x
    return resultado

In [213]:
reduce(array_example, suma)

np.int64(4950)

In [217]:
reduce(array_example[1:12], multiplica)

np.int64(39916800)

In [219]:
reduce(array_example, lambda listita: np.mean(listita))

np.float64(49.5)

In [246]:
my_data.agg({'salario': ['mean', lambda x: x.std()]})

salario
mean      43520.724700
<lambda>  10238.503475

In [247]:
my_data.transform({'salario': [lambda x: np.round(x, 2)]})

salario
    <lambda>
0   35631.59
1   53368.50
2   52673.34
3   47408.39
4   25012.28
..       ...
95  26066.76
96  48004.09
97  41881.69
98  43308.35
99  55129.20

[100 rows x 1 columns]

In [249]:
my_data.transform({'nombre': [lambda x: x.lower()]})

nombre
     <lambda>
0    nombre_0
1    nombre_1
2    nombre_2
3    nombre_3
4    nombre_4
..        ...
95  nombre_95
96  nombre_96
97  nombre_97
98  nombre_98
99  nombre_99

[100 rows x 1 columns]

In [14]:
my_data.transform({'datebirth': [lambda x: x[:4]], 'genero': [lambda x: x.lower() if x is not None else None]})

ValueError: Transform function failed

In [23]:
my_data['genero'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: genero
Non-Null Count  Dtype 
--------------  ----- 
99 non-null     object
dtypes: object(1)
memory usage: 928.0+ bytes


In [37]:
my_data.isna().sum()

nombre       0
edad         0
ciudad       0
salario      0
datebirth    0
genero       3
dtype: int64

In [42]:
my_data['genero'] = my_data['genero'].apply(lambda x: x.lower() if pd.notna(x) else x)

In [40]:
my_data['genero']

0     masculino
1     masculino
2     masculino
3     masculino
4      femenino
        ...    
95     femenino
96     femenino
97          NaN
98    masculino
99          NaN
Name: genero, Length: 100, dtype: object

In [63]:
my_data['genero'] = my_data['genero'].apply(lambda x: 'femenino' if x == 'femenin' else x)


In [48]:
my_data.loc[:, ['genero']].describe()

genero
count         97
unique         3
top     femenino
freq          52

In [58]:
my_data.loc[:, ['genero', 'salario', 'edad']].groupby('genero').sum()

salario  edad
genero                       
femenin    5.187137e+04    41
femenino   2.179688e+06  2135
masculino  1.964407e+06  1734

In [70]:
my_data = my_data[pd.notna(my_data['genero'])]

In [72]:
my_data.describe()

edad       salario
count  97.000000     97.000000
mean   40.309278  43257.389134
std    11.570761  10201.686310
min    18.000000  25012.284767
25%    32.000000  34709.957479
50%    41.000000  44684.006767
75%    50.000000  51328.527738
max    59.000000  59835.409428