# Clase 1 de arquitectura


_Ejemplo de celdas en jupyter_

In [3]:
x = 1
y = 8
x * y

8

_Las celdas tambien pueden importar clases_

In [4]:
import math
math.sin(math.pi/2)

1.0

_Los imports de otra celda funcionan en las celdas siguientes_

In [ ]:
math.ceil(3.1)

__La instalacion de numpy se hace ejecutando el comando__

`pip install numpy`

In [6]:
import numpy as np

In [9]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [10]:
my_array.ndim

1

In [11]:
my_array.shape

(5,)

In [12]:
my_array2 = np.array([[1, 2, 3], [4, 5, 6]])
my_array2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
my_array2.ndim

2

In [14]:
my_array2.shape

(2, 3)

In [15]:
my_array2.size

6

In [16]:
my_array3 = np.array([[1,2],[3,4],[5,6]])
my_array3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
my_array3.shape

(3, 2)

In [18]:
my_array_3d = np.array([[[1, 2], [3,4]], [[5,6], [7,8]]])
my_array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
my_array_3d.shape

(2, 2, 2)

In [20]:
my_array_3d[0][1][0]

np.int64(3)

In [21]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.random.random((2, 3))

array([[0.73470857, 0.05333784, 0.79377105],
       [0.59832392, 0.99004715, 0.52024632]])

In [27]:
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(5, 20, -2)

array([], dtype=int64)

In [30]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [33]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [38]:
np.arange(4, 20).reshape(4, 4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
np.arange(4, 20).reshape(4,4).flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
np.linspace(1, 100, 100).reshape(10, 10)

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [17]:
np.linspace(1, 100, 100)[ : :-1]

array([100.,  99.,  98.,  97.,  96.,  95.,  94.,  93.,  92.,  91.,  90.,
        89.,  88.,  87.,  86.,  85.,  84.,  83.,  82.,  81.,  80.,  79.,
        78.,  77.,  76.,  75.,  74.,  73.,  72.,  71.,  70.,  69.,  68.,
        67.,  66.,  65.,  64.,  63.,  62.,  61.,  60.,  59.,  58.,  57.,
        56.,  55.,  54.,  53.,  52.,  51.,  50.,  49.,  48.,  47.,  46.,
        45.,  44.,  43.,  42.,  41.,  40.,  39.,  38.,  37.,  36.,  35.,
        34.,  33.,  32.,  31.,  30.,  29.,  28.,  27.,  26.,  25.,  24.,
        23.,  22.,  21.,  20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,
        12.,  11.,  10.,   9.,   8.,   7.,   6.,   5.,   4.,   3.,   2.,
         1.])

In [22]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
np.arange(20).reshape(4, 5)[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
np.arange(20).reshape(4, 5)[:3, 1:]


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [27]:
np.arange(20).reshape(4, 5)[:3, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13]])

In [28]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
np.arange(20).reshape(4, 5)[:,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [31]:
np.arange(20).reshape(4, 5)[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [32]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
np.arange(20).reshape(4, 5)[1:,-2::-2]

array([[ 8,  6],
       [13, 11],
       [18, 16]])

In [42]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
np.arange(20).reshape(4, 5)[[1, 0, 3], [1, 3, 4]]

array([ 6,  3, 19])

In [46]:
arr = np.arange(20).reshape(4, 5)
arr[arr > 7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
arr[arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
def is_prime(n):
    if n == 0 or n == 1:
        return False
    i = 2
    while (i ** 2) <= n:
        if n % i == 0:
            return False
        i += 1
    return True

In [50]:
is_prime(20)

False

In [53]:
is_prime(19)

True

In [58]:
is_prime(139)

True

In [67]:
arr = np.arange(1000).reshape(100, 10).flatten()
np.array([x for x in arr if is_prime(x)])

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569,
       571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643,
       647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733,
       739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823,
       827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911,
       919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997])

In [75]:
np.arange(10).reshape(2, 5) - 1

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [77]:
np.arange(10).reshape(2, 5).max()

np.int64(9)

In [78]:
np.arange(10).reshape(2, 5).min()


np.int64(0)

In [79]:
np.arange(10).reshape(2, 5).sum()

np.int64(45)

In [81]:
np.arange(10).reshape(2, 5).transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [85]:
np.arange(10).reshape(2, 5).max(axis=0)

array([5, 6, 7, 8, 9])

In [87]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

In [88]:
a + b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [89]:
a * b

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [91]:
a.dot(b.reshape(5, 2))

array([[160, 170],
       [510, 545]])

In [ ]:
# n x m \dot m x n = n x n

In [2]:
import pandas as pd

In [3]:
s = pd.Series([1, 2,4, 5, 9])

In [4]:
s

0    1
1    2
2    4
3    5
4    9
dtype: int64

In [8]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [9]:
dates_serie = pd.date_range('20190101', periods=5)
dates_serie

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05'],
              dtype='datetime64[ns]', freq='D')

In [11]:
dates_serie = pd.date_range('20190101', periods=365)
dates_serie

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25',
               '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30', '2019-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [15]:
dates_serie = pd.date_range('20190101', periods=12, freq='ME')
dates_serie

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [20]:
dates_serie = pd.date_range('20241216', periods=10, freq='min')
dates_serie

DatetimeIndex(['2024-12-16 00:00:00', '2024-12-16 00:01:00',
               '2024-12-16 00:02:00', '2024-12-16 00:03:00',
               '2024-12-16 00:04:00', '2024-12-16 00:05:00',
               '2024-12-16 00:06:00', '2024-12-16 00:07:00',
               '2024-12-16 00:08:00', '2024-12-16 00:09:00'],
              dtype='datetime64[ns]', freq='min')

In [21]:
df = pd.DataFrame(
    {
        "Nombre": ['Yadira', 'Roman', 'Valeria', 'Rodrigo', 'Daniel'],
        "Color": ['Naranja', 'Foto', 'Foto', 'Naranja', 'Morado'],
        "Nonce": [2, 5, 4, 6, 7]
    }
)
df

Nombre    Color  Nonce
0   Yadira  Naranja      2
1    Roman     Foto      5
2  Valeria     Foto      4
3  Rodrigo  Naranja      6
4   Daniel   Morado      7

In [58]:
df = pd.DataFrame(
    {
        "Nombre": ['Yadira', 'Roman', 'Valeria', 'Rodrigo', 'Daniel'],
        "Color": ['Naranja', 'Foto', 'Foto', 'Naranja', 'Morado'],
        "Nonce": [2, 5, 4, 6, 7]
    }, index=[1, 2, 3, 4, 5]
)
df

Nombre    Color  Nonce
1   Yadira  Naranja      2
2    Roman     Foto      5
3  Valeria     Foto      4
4  Rodrigo  Naranja      6
5   Daniel   Morado      7

In [63]:
df.sort_values(by='Nombre', ascending=False)

Nombre    Color  Nonce
1   Yadira  Naranja      2
3  Valeria     Foto      4
2    Roman     Foto      5
4  Rodrigo  Naranja      6
5   Daniel   Morado      7

In [53]:
df.describe()

Nonce
count  5.000000
mean   4.800000
std    1.923538
min    2.000000
25%    4.000000
50%    5.000000
75%    6.000000
max    7.000000

In [38]:
df.dtypes

Nombre    object
Color     object
Nonce      int64
dtype: object

In [29]:
df.iloc[4]

Nombre    Daniel
Color     Morado
Nonce          7
Name: 5, dtype: object

In [64]:
df = pd.DataFrame(np.arange(1000).reshape(200, 5), index=pd.date_range('20241216', periods=200, freq='D'), columns=['A', 'B', 'C', 'D', 'E'] )
df

A    B    C    D    E
2024-12-16    0    1    2    3    4
2024-12-17    5    6    7    8    9
2024-12-18   10   11   12   13   14
2024-12-19   15   16   17   18   19
2024-12-20   20   21   22   23   24
...         ...  ...  ...  ...  ...
2025-06-29  975  976  977  978  979
2025-06-30  980  981  982  983  984
2025-07-01  985  986  987  988  989
2025-07-02  990  991  992  993  994
2025-07-03  995  996  997  998  999

[200 rows x 5 columns]

In [33]:
# REST API
df.head()

A   B   C   D   E
2024-12-16   0   1   2   3   4
2024-12-17   5   6   7   8   9
2024-12-18  10  11  12  13  14
2024-12-19  15  16  17  18  19
2024-12-20  20  21  22  23  24

In [34]:
df.tail()

A    B    C    D    E
2025-06-29  975  976  977  978  979
2025-06-30  980  981  982  983  984
2025-07-01  985  986  987  988  989
2025-07-02  990  991  992  993  994
2025-07-03  995  996  997  998  999

In [35]:
df.dtypes

A    int64
B    int64
C    int64
D    int64
E    int64
dtype: object

In [42]:
df.head(10)

A   B   C   D   E
2024-12-16   0   1   2   3   4
2024-12-17   5   6   7   8   9
2024-12-18  10  11  12  13  14
2024-12-19  15  16  17  18  19
2024-12-20  20  21  22  23  24
2024-12-21  25  26  27  28  29
2024-12-22  30  31  32  33  34
2024-12-23  35  36  37  38  39
2024-12-24  40  41  42  43  44
2024-12-25  45  46  47  48  49

In [43]:
df.tail(20)

A    B    C    D    E
2025-06-14  900  901  902  903  904
2025-06-15  905  906  907  908  909
2025-06-16  910  911  912  913  914
2025-06-17  915  916  917  918  919
2025-06-18  920  921  922  923  924
2025-06-19  925  926  927  928  929
2025-06-20  930  931  932  933  934
2025-06-21  935  936  937  938  939
2025-06-22  940  941  942  943  944
2025-06-23  945  946  947  948  949
2025-06-24  950  951  952  953  954
2025-06-25  955  956  957  958  959
2025-06-26  960  961  962  963  964
2025-06-27  965  966  967  968  969
2025-06-28  970  971  972  973  974
2025-06-29  975  976  977  978  979
2025-06-30  980  981  982  983  984
2025-07-01  985  986  987  988  989
2025-07-02  990  991  992  993  994
2025-07-03  995  996  997  998  999

In [44]:
df.index

DatetimeIndex(['2024-12-16', '2024-12-17', '2024-12-18', '2024-12-19',
               '2024-12-20', '2024-12-21', '2024-12-22', '2024-12-23',
               '2024-12-24', '2024-12-25',
               ...
               '2025-06-24', '2025-06-25', '2025-06-26', '2025-06-27',
               '2025-06-28', '2025-06-29', '2025-06-30', '2025-07-01',
               '2025-07-02', '2025-07-03'],
              dtype='datetime64[ns]', length=200, freq='D')

In [48]:
my_numpy_particles = df.to_numpy()
my_numpy_particles

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 1

In [51]:
df.describe()

A           B           C           D           E
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   497.500000  498.500000  499.500000  500.500000  501.500000
std    289.395923  289.395923  289.395923  289.395923  289.395923
min      0.000000    1.000000    2.000000    3.000000    4.000000
25%    248.750000  249.750000  250.750000  251.750000  252.750000
50%    497.500000  498.500000  499.500000  500.500000  501.500000
75%    746.250000  747.250000  748.250000  749.250000  750.250000
max    995.000000  996.000000  997.000000  998.000000  999.000000

In [57]:
df.sort_index(ascending=False)

A    B    C    D    E
2025-07-03  995  996  997  998  999
2025-07-02  990  991  992  993  994
2025-07-01  985  986  987  988  989
2025-06-30  980  981  982  983  984
2025-06-29  975  976  977  978  979
...         ...  ...  ...  ...  ...
2024-12-20   20   21   22   23   24
2024-12-19   15   16   17   18   19
2024-12-18   10   11   12   13   14
2024-12-17    5    6    7    8    9
2024-12-16    0    1    2    3    4

[200 rows x 5 columns]

In [65]:
df["D"]

2024-12-16      3
2024-12-17      8
2024-12-18     13
2024-12-19     18
2024-12-20     23
             ... 
2025-06-29    978
2025-06-30    983
2025-07-01    988
2025-07-02    993
2025-07-03    998
Freq: D, Name: D, Length: 200, dtype: int64

In [66]:
df[1:10]

A   B   C   D   E
2024-12-17   5   6   7   8   9
2024-12-18  10  11  12  13  14
2024-12-19  15  16  17  18  19
2024-12-20  20  21  22  23  24
2024-12-21  25  26  27  28  29
2024-12-22  30  31  32  33  34
2024-12-23  35  36  37  38  39
2024-12-24  40  41  42  43  44
2024-12-25  45  46  47  48  49

In [70]:
df['20241220':'20250106']

A    B    C    D    E
2024-12-20   20   21   22   23   24
2024-12-21   25   26   27   28   29
2024-12-22   30   31   32   33   34
2024-12-23   35   36   37   38   39
2024-12-24   40   41   42   43   44
2024-12-25   45   46   47   48   49
2024-12-26   50   51   52   53   54
2024-12-27   55   56   57   58   59
2024-12-28   60   61   62   63   64
2024-12-29   65   66   67   68   69
2024-12-30   70   71   72   73   74
2024-12-31   75   76   77   78   79
2025-01-01   80   81   82   83   84
2025-01-02   85   86   87   88   89
2025-01-03   90   91   92   93   94
2025-01-04   95   96   97   98   99
2025-01-05  100  101  102  103  104
2025-01-06  105  106  107  108  109