# Clase 1 de arquitectura


_Ejemplo de celdas en jupyter_

In [3]:
x = 1
y = 8
x * y

8

_Las celdas tambien pueden importar clases_

In [4]:
import math
math.sin(math.pi/2)

1.0

_Los imports de otra celda funcionan en las celdas siguientes_

In [ ]:
math.ceil(3.1)

__La instalacion de numpy se hace ejecutando el comando__

`pip install numpy`

In [2]:
import numpy as np

In [9]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [10]:
my_array.ndim

1

In [11]:
my_array.shape

(5,)

In [12]:
my_array2 = np.array([[1, 2, 3], [4, 5, 6]])
my_array2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
my_array2.ndim

2

In [14]:
my_array2.shape

(2, 3)

In [15]:
my_array2.size

6

In [16]:
my_array3 = np.array([[1,2],[3,4],[5,6]])
my_array3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
my_array3.shape

(3, 2)

In [18]:
my_array_3d = np.array([[[1, 2], [3,4]], [[5,6], [7,8]]])
my_array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
my_array_3d.shape

(2, 2, 2)

In [20]:
my_array_3d[0][1][0]

np.int64(3)

In [21]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.random.random((2, 3))

array([[0.73470857, 0.05333784, 0.79377105],
       [0.59832392, 0.99004715, 0.52024632]])

In [27]:
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(5, 20, -2)

array([], dtype=int64)

In [30]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [33]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [38]:
np.arange(4, 20).reshape(4, 4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
np.arange(4, 20).reshape(4,4).flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
np.linspace(1, 100, 100).reshape(10, 10)

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [17]:
np.linspace(1, 100, 100)[ : :-1]

array([100.,  99.,  98.,  97.,  96.,  95.,  94.,  93.,  92.,  91.,  90.,
        89.,  88.,  87.,  86.,  85.,  84.,  83.,  82.,  81.,  80.,  79.,
        78.,  77.,  76.,  75.,  74.,  73.,  72.,  71.,  70.,  69.,  68.,
        67.,  66.,  65.,  64.,  63.,  62.,  61.,  60.,  59.,  58.,  57.,
        56.,  55.,  54.,  53.,  52.,  51.,  50.,  49.,  48.,  47.,  46.,
        45.,  44.,  43.,  42.,  41.,  40.,  39.,  38.,  37.,  36.,  35.,
        34.,  33.,  32.,  31.,  30.,  29.,  28.,  27.,  26.,  25.,  24.,
        23.,  22.,  21.,  20.,  19.,  18.,  17.,  16.,  15.,  14.,  13.,
        12.,  11.,  10.,   9.,   8.,   7.,   6.,   5.,   4.,   3.,   2.,
         1.])

In [22]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
np.arange(20).reshape(4, 5)[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
np.arange(20).reshape(4, 5)[:3, 1:]


array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [27]:
np.arange(20).reshape(4, 5)[:3, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13]])

In [28]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
np.arange(20).reshape(4, 5)[:,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [31]:
np.arange(20).reshape(4, 5)[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [32]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
np.arange(20).reshape(4, 5)[1:,-2::-2]

array([[ 8,  6],
       [13, 11],
       [18, 16]])

In [42]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
np.arange(20).reshape(4, 5)[[1, 0, 3], [1, 3, 4]]

array([ 6,  3, 19])

In [46]:
arr = np.arange(20).reshape(4, 5)
arr[arr > 7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
arr[arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
def is_prime(n):
    if n == 0 or n == 1:
        return False
    i = 2
    while (i ** 2) <= n:
        if n % i == 0:
            return False
        i += 1
    return True

In [50]:
is_prime(20)

False

In [53]:
is_prime(19)

True

In [58]:
is_prime(139)

True

In [67]:
arr = np.arange(1000).reshape(100, 10).flatten()
np.array([x for x in arr if is_prime(x)])

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569,
       571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643,
       647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733,
       739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823,
       827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911,
       919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997])

In [75]:
np.arange(10).reshape(2, 5) - 1

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [77]:
np.arange(10).reshape(2, 5).max()

np.int64(9)

In [78]:
np.arange(10).reshape(2, 5).min()


np.int64(0)

In [79]:
np.arange(10).reshape(2, 5).sum()

np.int64(45)

In [81]:
np.arange(10).reshape(2, 5).transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [85]:
np.arange(10).reshape(2, 5).max(axis=0)

array([5, 6, 7, 8, 9])

In [87]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

In [88]:
a + b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [89]:
a * b

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [91]:
a.dot(b.reshape(5, 2))

array([[160, 170],
       [510, 545]])

In [ ]:
# n x m \dot m x n = n x n